### PR TITLE
Update borgbackup to 1.2.5

### PR DESCRIPTION
**Pull request by bbhtt**
1.2.5 includes a security fix https://github.com/borgbackup/borg/releases/tag/1.2.5

### CODE REVIEW

**Comment by bbhtt** [comment]
> Build [62134 failed](https://buildbot.flathub.org/#/builders/6/builds/62134)

```
ERROR   src.manifest: Failed to check archive libfuse/fuse-3.12.0.tar.xz with AnityaChecker: Error downloading upstream source: 404, message='Not Found', url=URL('https://github.com/libfuse/libfuse/releases/download/fuse-3.16.1/fuse-3.16.1.tar.xz')
```

**Comment by bbhtt** [comment]
Oh I missed that the legacy resolver was being used for borg (I copied the manifest directly from pip-generator). 

However I don't think using the legacy resolver is the correct solution here. All dependencies from pyproject.toml must be built or be present. setuptools-scm is not in the SDK.

Both are build deps only, I can add a cleanup rule if you want.

**Comment by bbhtt** [comment]
Seems to work fine.

**Comment by sophie-h** [comment]
Thanks for the PR!

Since Pika 0.6 does not provide a `borg check` feature, this new borg version does not change anything for Pika Backup. But I will happily pick your manifest for the next release.

**Comment by bbhtt** [comment]
Thanks

**Pull request closed without merging**
